# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4292de1f4ad0ab8357e0b1040ea8ca36cecb41783fe2ba57e33137e33309075a826e15baf732d509c11ffffd00bed58b9fa70f811e07d7e953ce09e829db982c

test:
  secret_key_base: c38e504e26d6544bdcac98f7ac9a2bf4c61ff9bcc3b2bb1b4ec7dfa6c1b16b01f9477b7ac6f31c85e4fc94c663039594acc3cf79813bf1a37ac9f40a72044ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
